### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by awfulminded** [solidjs/solid-router#165]
### Describe the bug

When im trying to use Router it says 

```
Uncaught ReferenceError: React is not defined
```

And nothing works after that error.
It used to work like 1-2 weeks ago in my projects, but now its not working on newest projects. 

```
App.tsx
```

```
import logo from './logo.svg';
import styles from './App.module.css';

function App() {
  return (
    <div class={styles.App}>
      <header class={styles.header}>
        <img src={logo} class={styles.logo} alt="logo" />
        <p>
          Edit <code>src/App.jsx</code> and save to reload.
        </p>
        <a
          class={styles.link}
          href="https://github.com/solidjs/solid"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Solid
        </a>
      </header>
    </div>
  );
}

export default App;
```

```
index.tsx
```

```
import { render } from 'solid-js/web';

import './index.css';
import App from './App';
import {Router} from 'solid-app-router'

render(() => <Router>
    <App />
</Router>, document.getElementById('root'));

```

its just default project but as soon as im adding Router it crashes

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

Start new project then npm i solid-app-router

### Expected behavior

1

### Platform

- OS: Windows
- Browser: Chrome

**Comment by abonshan** [comment]
I've got the exact same issue. I add the router with the package '@solidjs/router' on Windows or Mac with Chrome. and i get this message in the dev console:

components.jsx:11 Uncaught ReferenceError: React is not defined
    at Router (components.jsx:11:5)
    at dev.js:519:12
    at untrack (dev.js:425:12)
    at Object.fn (dev.js:515:37)
    at runComputation (dev.js:695:22)
    at updateComputation (dev.js:680:3)
    at devComponent (dev.js:526:3)
    at createComponent (dev.js:1228:10)
    at index.jsx:9:3
    at dev.js:99:53

**Comment by asafs94** [comment]
Same here

**Comment by dnguyenlearning** [comment]
me too.....

**Comment by ryansolid** [comment]
You all using Vite? I think they broke something. We are looking into it.

**Comment by bfsmith** [comment]
Same issue. I'm using Vite. Thanks for investigating.

**Comment by dnguyenlearning** [comment]
> You all using Vite? I think they broke something. We are looking into it.

yeah @ryansolid , we using vite, thank for your quick response..

**Comment by timothyallan** [comment]
I posted this in the discord as well, but to get things working again: downgrade to vite@3.0.9 and vite-plugin-solid@2.3.0

**Comment by dnguyenlearning** [comment]
> I posted this in the discord as well, but to get things working again: downgrade to vite@3.0.9 and vite-plugin-solid@2.3.0

downgradte to vite@3.0.9 and vite-plugin-solid@2.3.0 still not working for me

**Comment by timothyallan** [comment]
> > I posted this in the discord as well, but to get things working again: downgrade to vite@3.0.9 and vite-plugin-solid@2.3.0
> 
> downgradte to vite@3.0.9 and vite-plugin-solid@2.3.0 still not working for me

I just noticed that the project I got working with those versions is still using solid-app-router@0.4.2, and hadn't switched to the name changed @solidjs/router@0.4.3 yet. Try 0.4.2 as well?

**Comment by abonshan** [comment]
> > I posted this in the discord as well, but to get things working again: downgrade to vite@3.0.9 and vite-plugin-solid@2.3.0
> 
> downgradte to vite@3.0.9 and vite-plugin-solid@2.3.0 still not working for me

After the downgrade I get a new stack:

Uncaught TypeError: Comp is not a function
    at dev.js:519:12
    at untrack (dev.js:425:12)
    at Object.fn (dev.js:515:37)
    at runComputation (dev.js:695:22)
    at updateComputation (dev.js:680:3)
    at devComponent (dev.js:526:3)
    at createComponent (dev.js:1228:10)
    at shared.element.component.element.element [as outlet] (routing.js:47:21)
    at get children [as children] (components.jsx:57:64)
    at Object.fn (dev.js:972:35)

**Comment by awfulminded** [comment]
i have downgraded to ```vite@3.0.9``` and ```vite-plugin-solid@2.3.0``` + switched solid-app-router to ```@solidjs/router@0.4.3```
Now it seems to work perfectly. Thanks everyone :)

**Comment by abonshan** [comment]
> i have downgraded to `vite@3.0.9` and `vite-plugin-solid@2.3.0` + switched solid-app-router to `@solidjs/router@0.4.3` Now it seems to work perfectly. Thanks everyone :)

still no luck, got the same stack as before:

Uncaught TypeError: Comp is not a function at dev.js:519:12 at untrack (dev.js:425:12) at Object.fn (dev.js:515:37) at runComputation (dev.js:695:22) at updateComputation (dev.js:680:3) at devComponent (dev.js:526:3) at createComponent (dev.js:1228:10) at shared.element.component.element.element [as outlet] (routing.js:47:21) at get children [as children] (components.jsx:57:64) at Object.fn (dev.js:972:35)

**Comment by P233** [comment]
> i have downgraded to `vite@3.0.9` and `vite-plugin-solid@2.3.0` + switched solid-app-router to `@solidjs/router@0.4.3` Now it seems to work perfectly. Thanks everyone :)

I got the same issue, and it works!

**Comment by dnguyenlearning** [comment]
> i have downgraded to `vite@3.0.9` and `vite-plugin-solid@2.3.0` + switched solid-app-router to `@solidjs/router@0.4.3` Now it seems to work perfectly. Thanks everyone :)

hmm, do the same with your suggest and have no luck. still can't do anything...

**Comment by thatsbrandon** [comment]
I have this problem still. Using `@solidjs/router`. The team is launching a new product soon & this is the worst time for this bug to appear.

Current versions :
```json
    "vite": "^3.1.2",
    "vite-plugin-solid": "^2.3.3"
```

**Comment by thatsbrandon** [comment]
> > i have downgraded to `vite@3.0.9` and `vite-plugin-solid@2.3.0` + switched solid-app-router to `@solidjs/router@0.4.3` Now it seems to work perfectly. Thanks everyone :)
> 
> hmm, do the same with your suggest and have no luck. still can't do anything...

You might have ran into the same issue I did, make sure you fully delete a reload those two packages :)

**Comment by lukesmurray** [comment]
I think I found the potential issue in `vite-plugin-solid` https://github.com/solidjs/vite-plugin-solid/commit/6aff8d9a8af44a4a3da8b817b758600db9adc006#commitcomment-84435573

**Comment by Lightnet** [comment]
Manage to find simple fixed. Tested other projects base on vite and guessing default settings.
```js
export default defineConfig({
  optimizeDeps:{
    disabled: true, // this remove react is not defined
  },
  plugins: [
    solidPlugin()
  ],
});
```

**Comment by ryansolid** [comment]
Sorry for the issue. We were too zealous trying to fix something in SolidStart.. This should be fixed as is with vite-plugin-solid 2.3.6

**Comment by GutsTang** [comment]
> Manage to find simple fixed. Tested other projects base on vite and guessing default settings.
> 
> ```js
> export default defineConfig({
>   optimizeDeps:{
>     disabled: true, // this remove react is not defined
>   },
>   plugins: [
>     solidPlugin()
>   ],
> });
> ```

My hero. You saved my life.

**Comment by wellloy1** [comment]
This problem is still happening on Win 10, my versions:
	"vite": "^4.1.1",
	"vite-plugin-solid": "^2.5.0"
	"solid-js": "^1.6.10"

I try to use a simple JSX icons but getting a ReferenceError: React is not defined on a keyword "return".
